/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Contact = IDL.Record({
  'linkedin' : IDL.Text,
  'instagram' : IDL.Text,
  'phone' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'fileBlobKey' : IDL.Opt(IDL.Text),
});
export const Resume = IDL.Record({
  'blobKey' : IDL.Text,
  'filename' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'deleteProject' : IDL.Func([IDL.Text], [], []),
  'getAbout' : IDL.Func([], [IDL.Text], ['query']),
  'getContact' : IDL.Func([], [Contact], ['query']),
  'getProfilePhoto' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getResume' : IDL.Func([], [IDL.Opt(Resume)], ['query']),
  'getVisitors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'recordVisitor' : IDL.Func([IDL.Text], [], []),
  'setProfilePhoto' : IDL.Func([IDL.Text], [], []),
  'setResume' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateAbout' : IDL.Func([IDL.Text], [], []),
  'updateContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Contact = IDL.Record({
    'linkedin' : IDL.Text,
    'instagram' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'fileBlobKey' : IDL.Opt(IDL.Text),
  });
  const Resume = IDL.Record({ 'blobKey' : IDL.Text, 'filename' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'deleteProject' : IDL.Func([IDL.Text], [], []),
    'getAbout' : IDL.Func([], [IDL.Text], ['query']),
    'getContact' : IDL.Func([], [Contact], ['query']),
    'getProfilePhoto' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getResume' : IDL.Func([], [IDL.Opt(Resume)], ['query']),
    'getVisitors' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'recordVisitor' : IDL.Func([IDL.Text], [], []),
    'setProfilePhoto' : IDL.Func([IDL.Text], [], []),
    'setResume' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateAbout' : IDL.Func([IDL.Text], [], []),
    'updateContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };